# list of terminals
Term_var_name: 
Term_sep: 
Term_real_sep: [;|\n]
Term_space:    [\t\r]* # TODO

sep                  -> Term_space Term_real_sep Term_space
statements           -> statement [ sep statement, sep ... ]
statement            -> declaration | flow_construct
delcaration          -> variable_declaration | block_declaration | class_declaration
block_declaration    -> named_block_declaration | function_declaration
class_declaration    -> class Term_class_name
variable_declaration -> var_modifier variables '=' expression
variables            -> Term_varname | '(' Term_varname [ ',' Term_varname ',' ... ] ')'
expresion            -> builtin_object_declaration | do_block | literal | tenary_op
flow_construct       ->

# parsing algorithm

list of parsing functions

-
-
-
-

Parse
